# Generated by Django 3.2.16 on 2022-12-22 14:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentspage_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='page',
            field=modelcluster.fields.ParentalKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='parent_page', to='agents.agentspage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentspage',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agents'),
        ),
    ]
