# Generated by Django 3.2.16 on 2022-12-22 15:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20221222_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='page',
        ),
        migrations.RemoveField(
            model_name='agentspage',
            name='advert',
        ),
        migrations.AlterField(
            model_name='agentsconnection',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='agents.agents'),
        ),
        migrations.AlterField(
            model_name='agentsconnection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='agents.agentspage'),
        ),
    ]
