# Generated by Django 3.2.16 on 2022-12-22 16:15

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentspage_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentspage',
            name='agents',
            field=modelcluster.fields.ParentalManyToManyField(to='agents.Agents'),
        ),
    ]
