# Generated by Django 3.2.16 on 2022-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_auto_20221222_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='parent',
        ),
        migrations.AddField(
            model_name='agentspage',
            name='agents',
            field=models.ManyToManyField(to='agents.Agents'),
        ),
    ]
