# Generated by Django 3.2.16 on 2022-12-26 15:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20221226_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsconnection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_agents', to='agents.agentspage'),
        ),
    ]
