# Generated by Django 3.2.16 on 2023-01-03 14:11

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agents_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='first_parent',
            field=models.CharField(blank=True, default=agents.models.Agents.first_parent, max_length=255),
        ),
    ]
