# Generated by Django 3.2.16 on 2023-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agents_first_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentspage',
            name='first_parent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agents',
            name='first_parent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
