# Generated by Django 3.2.16 on 2023-01-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_auto_20230103_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentspage',
            name='first_parent',
        ),
    ]
