# Generated by Django 3.2.16 on 2022-12-21 08:45

from django.db import migrations
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appsalesforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True},
        ),
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='Title',
            field=salesforce.fields.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
