# Generated by Django 3.2.16 on 2022-12-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsalesforce', '0002_auto_20221221_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'base_manager_name': 'base_manager'},
        ),
    ]
