version: "3.9"

services:
  web-app:
    container_name: website
    build:
      context: .
    image: website_image
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database
    command: bash -c "poetry run python3 /usr/src/app/manage.py runserver  0.0.0.0:8000"

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres_data:
