SALESFORCE_USERNAME = 'alex.kubyk-dt2h@force.com'
SALESFORCE_PASSWORD = 'Salesforce-86'
SALESFORCE_SECURITY_TOKEN = 'v2mvoel5QRPhM0qChzfNPYPP'
SALESFORCE_INSTANCE = 'studiopresto.my.salesforce.com'
SALESFORCE_USE_SANDBOX = False