# Generated by Django 3.2.16 on 2023-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_title_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='first_parent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
